package com.xframe.common.model;

import com.xframe.common.model.base.BaseOldNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OldNews extends BaseOldNews<OldNews> {
	
}
